services:
  cassandra:
    image: bitnami/cassandra:5.0.2-debian-12-r6
    hostname: cassandra
    restart: unless-stopped
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - cassandra_data_dir:/bitnami/cassandra:z
      - ./docker/cassandra/init:/docker-entrypoint-initdb.d:z
    environment:
      CASSANDRA_DELAY_START_TIME: 0
      CASSANDRA_CFG_YAML_SASI_INDEXES_ENABLED: true
      CASSANDRA_CFG_YAML_READ_REQUEST_TIMEOUT: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

volumes:
  cassandra_data_dir:
